### ISSUE TITLE
Merge ethereum-cat-herders into the ethereum org

### ISSUE THREAD

**Issue by Pandapip1** [ethcatherders/EIPIP#132]
I suggest that the repositories in `ethereum-cat-herders` be transferred to the `ethereum` organization and that a new team (`@ethereum/cat-herders`) be made with admin rights over the transferred repos.

Rationale:
- Doing so would increase the discoverability of the ECH programs.
- If the EIP insight, EIPIP meetings, and other ECH programs become actually part of Ethereum, then they ~~may~~ will seem more official.
- The Ethereum foundation has money. Not sure if they'd give you any, but it'd be worth a shot :)
- Other reasons I can't remember. I'll update this issue when I think of them.

**Comment by dtedesco1** [comment]
I agree with the issues you raise. When I started learning about Ethereum governance earlier this year, it took me a few weeks of digging before I even realized ECH existed!

However, I'm not sure transferring the repos to the `ethereum` organization is the best way to address the issues. The lack of discoverability and officialness might occur partly because of how muddled the official website is. For instance, the [governance page](https://ethereum.org/en/governance/) is an overwhelming word salad about anything related to governance. Same goes for the [get involved page](https://ethereum.org/en/community/get-involved/) for anyone who is looking for a way to get involved.

I think editing those pages to offer a more prominent and simpler description of ECH's role (and maybe cleaning up the site content generally, while we're at it) might suffice. What do you think?

**Comment by xinbenlv** [comment]
I love for the `ethereum` github organization to properly disclose the ownership and adminship somewhere.

**Comment by poojaranjan** [comment]
No significant progress was noted. 
Closing the issue. If people want to resurface, please feel free to re-open the issue.
