### ISSUE TITLE
GitPoap badges

### ISSUE THREAD

**Issue by axic** [ethcatherders/EIPIP#134]
Following up a conversation with @colfax23 who is behind https://gitpoap.io, a system to issue badges for github contributors.

If it were to be issued for EIP contributions, I think the following repos should be included:
- https://github.com/ethereum/EIPs
- https://github.com/ethereum/eipv
- https://github.com/ethereum/EIP-Bot
- https://github.com/ethereum/eip_validator
- https://github.com/eip-automerger/automerger

I'll defer the more in depth explanation to @colfax23.

**Comment by MicahZoltu** [comment]
I would personally like to see GitPOAP drop the requirement for read access to GitHub private profile data before signal boosting them.

**Comment by colfax23** [comment]
@MicahZoltu you are definitely right, we just deployed an update to only request public profile data.  Appreciate the feedback and let us know if you find anything else.

We'd love to onboard and support the EIP repos!  For now the primary use-case of GitPOAP is for recognizing community contributions to open source and allowing contributors to configure their profile/digital resume (ex https://www.gitpoap.io/p/gnidan.eth).  

Over time as we build up this on-chain record of contribution, we aim to build even more useful coordination tooling, on-chain public goods funding, project & contributor discovery, etc.

We're also eager to hear from maintainers on what challenges you are facing and what we could possibly build to help.  Happy to answer any questions if you have them!

**Comment by MicahZoltu** [comment]
With the aforementioned change I'm generally fine with doing this if one of the other editors wants to champion the process.  I don't have the bandwidth to expend much energy on it myself though.

**Comment by colfax23** [comment]
Great! All we need from your side is consent, then we'll go forward with integrating.  Is there anyone else we should check with before we do?  Since it's all open source we can pull contributor lists automatically and there's nothing you need to do on your end. 

The only remaining step would be the POAP design - our design team will work on some concepts and we'll share with you here to get your feedback.

**Comment by poojaranjan** [comment]
In my chat with @colfax23, I didn't talk about below repos because I am not aware of it's current role and maintainers. 

Does anyone know if these are active repos? where do we use it in the EIP editing process? Last commit seems to be old.

- https://github.com/ethereum/eip_validator
- https://github.com/eip-automerger/automerger

CC: @MicahZoltu @axic @SamWilsn @lightclient @gcolvin

**Comment by colfax23** [comment]
Even if they aren't currently active, it does make sense to include them in the integration since we'll be awarding GitPOAPs to all contributors going back in history.

As we integrate funding mechanisms on top of GitPOAP, we plan for these historical record to inform retroactive public goods funding.

**Comment by lightclient** [comment]
@poojaranjan neither are active.
--

I'm spoke with some other people about doing this and it seems like we're good to go. As discussed on our call, I think the EIP repo is a bit special in what a "desirable" contribution is. For that reason, I think it's important to have a separate mechanism for awarding POAPs there.

**Comment by Pandapip1** [comment]
@colfax23 would it be possible for you to make a GitHub action that could be used to assign GitPOAPs to GitHub PRs?

**Comment by colfax23** [comment]
Sounds great, and makes total sense.  Thanks @lightclient.

@Pandapip1 great suggestion, we've been discussing something like that as we develop the ability to issue GitPOAPs 'ad hoc'.  Let me discuss this with the team and I'll let you know.

**Comment by Pandapip1** [comment]
My discord username#discrim is Pandapip1#8943 (I'm also on the ECH discord). Feel free to contact me!

**Comment by poojaranjan** [comment]
Closing, as not in active discussion. Champions may re-open or create a new discussion to bring it back to the EIPIP agenda.
