### ISSUE TITLE
Call for Input: Allow Links to CAIP

### ISSUE THREAD

**Issue by SamWilsn** [ethcatherders/EIPIP#320]
## Call for Input

<table>
<tr>
<th>Decision</th>
<td>

Do we merge https://github.com/ethereum/EIPs/pull/8247 ?

</td>
</tr>
<tr>
<th>If Affirmed</th>
<td>

Links to [CAIP](https://github.com/ChainAgnostic/CAIPs) proposals are allowed.

</td>
</tr>
<tr>
<th>If Rejected</th>
<td>No change.</td>
</tr>
<tr>
<th>Method</th>
<td>Rough Consensus</td>
</tr>
<tr>
<th>Deadline</th>
<td>March 21th, 2024</td>
</tr>
</table>

# Background

See https://github.com/ethereum/ERCs/pull/99

**Comment by g11tech** [comment]
i am of the opinion that we allow as much links as possible to the sources which we deem to be safe to refer (immutability and reputation wise)

**Comment by bumblefudge** [comment]
^ I would be glad to open a PR that consolidates the allowlist into a simple two-column table with domains (reputation) and regexs (CI-able immutability-check), since each source has a different URL/URN scheme for its immutable docs (and non-immutable docs we presumably don't want to allow links to).  

In the case of CAIPs, it might be easier to do allow rendered CAIPs (domain `chainagnostic.org`) and check a `<meta>` tag I can rejigger jekyll to include in each rendered page containing it's document status?

**Comment by SamWilsn** [comment]
I wanted to avoid commenting on this one since I wrote [EIP-5757](https://eips.ethereum.org/EIPS/eip-5757), but since no one has discussed whether CAIPs meet the requirements there, I guess I probably should:

**Versioned:** Yes; git hashes.
**Availability:** Questionable; only existed since August of 2019.
**No Cost:** Yes; repository is CC0-1.0.

---

My two concerns are:

* CAIPs haven't been around that long. 5757 mentions ten years as a reasonable benchmark.
* Can't we just copy the CAIP into the assets directory and link to it from there? CC0 would allow that.

---

Since we have a reasonable workaround (copying to assets), and the only availability benchmark we have hasn't been met, I am going to **oppose** this CFI.

**Comment by SamWilsn** [comment]
There's also the question of legitimacy, which I neglected to bring up earlier. While it isn't an official requirement, do we want to recognize CAIPs as a "legitimate" standards body? If we, so should link to them. If not, put them in `assets/`.
